apiVersion: v2
name: fluentd
description: A Helm chart for fluentd
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../../application/common