# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: fluent/fluentd-kubernetes-daemonset:v1.16-debian-elasticsearch8-1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

rbac:
  create: true
  annotations: {}
  role:
    resources: ["pods","namespaces"]
    verbs: ["get", "list", "watch"]
  rolebinding:
    subjects:
      - kind: ServiceAccount
        name: fluentd
        namespace: logging

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

env:
  - name: FLUENT_ELASTICSEARCH_HOST
    value: elasticsearch
  - name: FLUENT_ELASTICSEARCH_PORT
    value: "9200"

service:
  type: ClusterIP
  port: 24231

ingress:
  enabled: false

autoscaling:
  enabled: false

fileConfig:
  enabled: true
  name: config-volume

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}