version: "3.8"
services: 
  mysql-service:
    image: mysql
    container_name: mysql-service
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PORT: ${DB_PORT}
    volumes:
      - db:/var/lib/mysql
    networks:
      - dkhp-network
  flyway-service:
    image: dkhp-flyway
    container_name: flyway-service
    depends_on:
      - mysql-service
    environment:
      DB_HOST: mysql-service
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
    networks:
     - dkhp-network   
  # Spring boot server connect to database
  backend-service: 
   image: hungtran679/dkhp_demo-backend-service
   container_name: backend-service
   depends_on:
     - mysql-service
     - flyway-service
   environment:
      DB_HOST: mysql-service
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
   ports:
      - 8080:8080
   networks:
     - dkhp-network
networks:
  dkhp-network:

volumes:
  db: