# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hungtran679/dkhp_demo-backend-service:latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

env:
  - name: DB_HOST
    value: mysql             
  - name: DB_PORT
    valueFrom:
      configMapKeyRef:
        name: mysql
        key: DB_PORT         
  - name: DB_DATABASE
    valueFrom:
      configMapKeyRef:
        name: mysql
        key: DB_DATABASE
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: mysql
        key: DB_USER
  - name: DB_PASS
    valueFrom:
      secretKeyRef:
        name: mysql
        key: DB_PASS

pvc:
  enabled: false

job:
  enabled: true
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
  imagePullSecrets: []
  image: "hungtran679/dkhp-flyway:latest"
  pullPolicy: IfNotPresent
  env:
    - name: DB_HOST
      value: mysql             
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: mysql
          key: DB_PORT         
    - name: DB_DATABASE
      valueFrom:
        configMapKeyRef:
          name: mysql
          key: DB_DATABASE
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: mysql
          key: DB_USER
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: mysql
          key: DB_PASS
  restartPolicy: OnFailure

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - paths:
        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}