# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hungtran679/dkhp_demo-frontend-service:latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: false
  annotations: {}
  role:
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  rolebinding:
    subjects:
      - kind: ServiceAccount
        name: nginx-exporter
        namespace: monitoring

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

env:
  - name: API_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: backend
        key: API_ENDPOINT

pvc:
  enabled: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
  - host: frontend.local
    paths:
      - path: /
        pathType: Prefix
  tls: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}