{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end}}