FROM openjdk:17-jdk-alpine
MAINTAINER com.HungTran
# COPY /target/demo-0.0.1-SNAPSHOT.war demo-0.0.1-SNAPSHOT.war
WORKDIR /app/backend/target
ENTRYPOINT ["java","-jar","demo-0.0.1-SNAPSHOT.war"]
