# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

env:
  - name: discovery.type
    value: single-node
  - name: ES_JAVA_OPTS
    value: "-Xms512m -Xmx512m"
  - name: xpack.security.enabled
    value: "false"
  - name: "NAMESPACE"
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace

pvc:
  enabled: true
  accessMode: ReadWriteOnce
  storage: 500M
  pvName: elasticsearch-pv
  mountPath: /usr/share/elasticsearch/data

service:
  type: ClusterIP
  port: 9200

ingress:
  enabled: false

autoscaling:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}