global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s

rule_files:
  - "./rules/*.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: mysql-exporter
    static_configs:
       - targets: ['mysql-exporter:9104']
  - job_name: backend-exporter
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['backend-service:8080']
  - job_name: nginx-exporter
    static_configs:
        - targets: ['nginx-exporter:9113']
    

