# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana:8.5.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

env:
  - name: ELASTICSEARCH_HOSTS
    value: http://elasticsearch:9200
  - name: XPACK_MONITORING_ENABLED
    value: "false"
  - name: XPACK_SECURITY_ENABLED
    value: "false"

pvc:
  enabled: false

service:
  type: ClusterIP
  port: 5601

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
  - host: kibana.local
    paths:
      - path: /
        pathType: Prefix
  tls: []

autoscaling:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}